kubectl delete -f /artifacts/cert-manaer.yaml
kubectl delete -f /artifacts/confimap.yaml
kubectl delete -f /artifacts/operator-service-account-rbac.yaml
kubectl delete -f /artifacts/postres-operator.yaml
kubectl delete -f /artifacts/api-service.yaml
kubectl delete -f /artifacts/psql.yaml
kubectl delete -f /artifacts/crds.yaml
kubectl delete -f /artifacts/operator.yaml
kubectl delete -f /artifacts/elastic.yaml
