apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: xcp-trust-anchor
  namespace: tsb
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJRENDQWdpZ0F3SUJBZ0lSQUlZcmJqbE5ZV3JzNzdkdXUxVzNkVHd3RFFZSktvWklodmNOQVFFTEJRQXcKR1RFWE1CVUdBMVVFQXhNT2VHTndMblJsZEhKaGRHVXVhVzh3SUJjTk1qRXdPREV3TURBeU9ETXpXaGdQTWpFeQpNVEEzTVRjd01ESTRNek5hTUJreEZ6QVZCZ05WQkFNVERuaGpjQzUwWlhSeVlYUmxMbWx2TUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdHJzeVlIa0tBaTEvLzlrNU5qSXZzYlVjelJ0V3NDS0IKQWlSVkhCaEtIMHhDSEZkdTFpdmJuZ0t2MjA1NldGQTV2ZlM3OFFDM2tiV2pKUjE5UURkSUJCbkVHTGhMUXROOApnNkdQd09ncFZvczVzeEIwakpYUjN5QUNUL0ZLSVgrd1dpOTlUUDVlRGNkZDNVUEVZMU5rUkZCRUpHclV3ck9MClJCcytYVnFjK1VtQWFTbEVyRi9ST2pOb2tZOERSQkFZWGNBWUN1WnVPNEl2dGZEOERzWXlnNmhVMitGdFFicGkKRE05Q3JtZGVyTXhTR0FHdDcxNGh6MnhYbXhQVE5ESDE3bmR5czcwU3hRYlBQZHpCZis5UW42TGd6ZWIyUnBOQgpRU0k5NFZKcy85MERzbGdyekhBQWJpNkxpbUFSL25HWUsyblJzSzV6VjVEUzNnNXZPSENkUVFJREFRQUJvMkV3Clh6QU9CZ05WSFE4QkFmOEVCQU1DQXFRd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUMKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRk1pY0NUMThGUEFUbjM0ZURhQUova2RTZCtVZQpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJqakU2RW9GSWw4b2JTUWpmdElwZ2EwV0xyd0xybDgzdU5rK3JxCnRMWHEwTGxTeVhhREoyVTVZQkVLT1RMdmlPdjlodzlGS0VzZ0tkRnRpT09mSkhhVEhVNXBsOVJOc0xxLzl5c1cKOXNtakJyQ1hEemRYZ0RnYk1yck1meE1Yait6b2phZ1NGbEE5SFRXcnozUndkZkN6ekFIRkg1aVJSblpnbkptQgo4b1k4SW53L0cram5VaDcxRUk2eXFWNVl1eUNIRG5MTmpoVWJKMUdEOEY1RTdvYkNPQVJJWUM4dmpVZEpuMm96CmlUME82YlZ3eERIOWEvbkVUemJ0c1RZMzlkTFpFT0FwR2ViYmk4bUJBbXZzWEpwTmIxa0k0RDlpQlUvRy8yN28KbzJkYzA5cHoyQ2VleDBqU1RCc1FGdzNPaFZPdExuU2NYY3ZEa1pnNGV1RGs3NGw3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdHJzeVlIa0tBaTEvLzlrNU5qSXZzYlVjelJ0V3NDS0JBaVJWSEJoS0gweENIRmR1CjFpdmJuZ0t2MjA1NldGQTV2ZlM3OFFDM2tiV2pKUjE5UURkSUJCbkVHTGhMUXROOGc2R1B3T2dwVm9zNXN4QjAKakpYUjN5QUNUL0ZLSVgrd1dpOTlUUDVlRGNkZDNVUEVZMU5rUkZCRUpHclV3ck9MUkJzK1hWcWMrVW1BYVNsRQpyRi9ST2pOb2tZOERSQkFZWGNBWUN1WnVPNEl2dGZEOERzWXlnNmhVMitGdFFicGlETTlDcm1kZXJNeFNHQUd0CjcxNGh6MnhYbXhQVE5ESDE3bmR5czcwU3hRYlBQZHpCZis5UW42TGd6ZWIyUnBOQlFTSTk0VkpzLzkwRHNsZ3IKekhBQWJpNkxpbUFSL25HWUsyblJzSzV6VjVEUzNnNXZPSENkUVFJREFRQUJBb0lCQUQwTnROcEk5dEFkZGJ2OQpUMEZOYVdRZDJGNnJlTDVtK09YSFQreVFMUXZpQmVERVVkTWJXa2lrS3kvQ085eVFDWXJ2WDNBNXhodllMWWQwCkgrbzV6a1VZZXMycm5mSFpDYXhOYWVPUmJtWnRKRDB4RFUvL3F0eTdMQ3FidXlJUU1OTWhOT05weGZFaW9Ma1MKTUdiamNRZm1MYTVoUjI4NllCakVaWVQ1aHFNL25DQlUvaERTTHNkemI1cFJPelBQeitRdFYwWjB0M1FlcG1STgpJdnRRT0h2TSs0eVRMeGhuQ1ljVUlSTnFLMjgzM21GOEl1UkI4dG94WXlWaWtlM1ltZlpLQlhKVDJKbnM2dGpCCjgweHpoRnpRdkl4QXZ0TG5yaml1YUpVNHByZDNmOHFXNm1rYmh3RW0xNUZnS0lKeVU1MDhWTmhnU3FyT0s4YmYKRFhPOE9yRUNnWUVBMGQrWFl4RzZYUHhDK1U5bXNmNmtFZEg1SjFWVkNVMnVwbSt2VUVQd2tNemJKd0JCZkdTVQo4NzBqNjIwMHQvWFpoQjdMV2ppUldwNGF1SU5sOEJiSGQ2K2dLZkRxY2tXZi9haWxOWDQwdTE5SG5lRnlTOGNpClcrUjhEUHg0a0NrRmtvRHBDb2RDejd3RVVhaVdyc0hqUHVLdFRaeVExUStxRmJpWFRwZnNqRzBDZ1lFQTN1UjMKZldQaDNkMFdiaGVhbEllUjdueGdrVlhzVkNSN0lrUEZseElINnVCd2tlRmtQLzU1Mm1mZnR4U0w4eG1KTkIxTwo2N0daWi9lTTRUSldtUVlIRUFYbnpvekZlYXlYNW94L2IwL2x6cU9jM2h5R3Jsd212K0JDbldSRkF5WktzS1BBCnl0TnlQSTN5bldUaDFjZGp4K0FYQ2dia051Z3pLeC9BR1hsN3A2VUNnWUVBamw0WGlzdlcyUWNDdzY1NklwcHoKWCtkSkZjYU1CZUNkYmlmckRBN2FYTStxaGwxbER1WUlLUU9RSHo4WWVRWWNSTVRDKzNQT0htT01Dc2lQMlBzSwoyb1RYcUR2V1BpZys3TXAvTDdkcVBBVFpSeDlNOGx5bVVTSEFpT3FuT2x1cGZRVlhrSjNLMDdKZVY2cCtkUlB2CmZKUTJMYVRjbHJ1bWpFK0l6SGJBcjAwQ2dZQW9MRDF0R0NlSmVXT2xqQk9NV2JMdnJQTXF2clhOcEpXYzQySWwKakZabyt2TFBHRFNkWkJ4S1JSYUpST2JFZGdISXBzK21vMmZtMlROSEUyK1FQUW5nMVcrbVJyRUE4UjZmcXdyOAo0UVdtYk03RktaY01yZ2M5NWdtYm5Jcmp1bThUenkvY1hxZmtTaUZFUlA1L0xXVEtqWlVaZFl5RWFPMXdCRlQzClFuSUxFUUtCZ0cwVWVBM09wRHJJcnJvRGplVEtady9iV2VFaDhCTTlKaytpVWI2MzFodzBIek5zTFdyM0ZhNjQKNklNaGFOeW95c3doTngrNENkcGtkNVFLcjBRbGJTZkRqZThqSVd1ck1nTG9Ydmc4NmV4WVZQQnJudDBUUUt2eApHV2ptb0tjVFRRaG5jVGM0cGk1aTFCdlRxL00vdnlFb3VZd1Y1enB0bDc5QTB1Q04vYlk1Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: xcp-trust-anchor
  namespace: tsb
spec:
  ca:
    secretName: xcp-trust-anchor
---
# to create root CA
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xcp-identity-issuer
  namespace: tsb
spec:
  secretName: xcp-identity-issuer
  issuerRef:
    name: xcp-trust-anchor
    kind: Issuer
  duration: 30000h
  isCA: true
  commonName: ca.xcp.tetrate.io
  uris:
    - spiffe://xcp.tetrate.io/ca
  usages:
    - cert sign
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: xcp-identity-issuer
  namespace: tsb
spec:
  ca:
    secretName: xcp-identity-issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xcp-central-cert
  namespace: tsb
spec:
  secretName: xcp-central-cert
  issuerRef:
    name: xcp-identity-issuer
    kind: Issuer
  duration: 30000h
  isCA: false
  dnsNames:
    # XCP is exposed through front-envoy
    - "envoy.tsb.svc.cluster.local"
    - "envoy.tsb.svc.cluster.local:9443"
  uris:
    - spiffe://xcp.tetrate.io/central
  usages:
    - server auth
    - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mpc-certs
  namespace: tsb
spec:
  secretName: mpc-certs
  issuerRef:
    name: xcp-identity-issuer
    kind: Issuer
  duration: 30000h
  isCA: false
  dnsNames:
    - "mpc.tsb.svc.cluster.local"
  uris:
    - spiffe://xcp.tetrate.io/mpc
  usages:
    - client auth
    - server auth
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-credentials
  namespace: tsb
type: Opaque
data:
  admin: "OGM2OTc2ZTViNTQxMDQxNWJkZTkwOGJkNGRlZTE1ZGZiMTY3YTljODczZmM0YmI4YTgxZjZmMmFiNDQ4YTkxOA=="
---
apiVersion: v1
kind: Secret
metadata:
  name: tsb-certs
  namespace: tsb
type: kubernetes.io/tls
data:
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZRakNDQXlxZ0F3SUJBZ0lERUFJU01BMEdDU3FHU0liM0RRRUJDd1VBTUVVeEN6QUpCZ05WQkFZVEFsVlQKTVE4d0RRWURWUVFJREFaRVpXNXBZV3d4RERBS0JnTlZCQW9NQTBScGN6RVhNQlVHQTFVRUF3d09kR05qTG5SbApkSEpoZEdVdWFXOHdIaGNOTVRrd05qQTFNVFF4TlRNeldoY05Nemd3T0RBME1UUXhOVE16V2pCYk1Rc3dDUVlEClZRUUdFd0pWVXpFUE1BMEdBMVVFQ0F3R1JHVnVhV0ZzTVJRd0VnWURWUVFIREF0VGNISnBibWRtYVdWc1pERU0KTUFvR0ExVUVDZ3dEUkdsek1SY3dGUVlEVlFRRERBNTBZMk11ZEdWMGNtRjBaUzVwYnpDQ0FTSXdEUVlKS29aSQpodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUs1VFZ6TzdUVHp0aEtuQ0Q5Y1ptOVpMMU1vQVFRVTJseFBHClNrNTNBSURlV2NLQ2R3Tk56VnhHR1FvZEgzZlAxQ1ZWcEU5d0tuTGswOUczamhjVVR6QkgzQytzOGRPekdpS2gKWFJJelFja1JyOEdPbXhJRlNxN1lFZlpKampzR0tmWUplTFgrclRCSHFpaFQ1c2cyUmhXM1p3QXU1QXN5L1hnRwpFQ3N3SFRhdmpabzE5cmN5RTl5UkV0WDdpMStjVFg0ZFZZdU5acGR5VEFTUjlqTmdiUlcxdFRJcFpHOHRZUTAwCmRYN2pPK2FrRnZuRklBaGprWFl3VVBnWGhlMHFESmpYMjRJd3EwU3pFMVZtb3FYekppTFBiT2tRZVlZY3djNGoKSlZqNnAzUWNHTDR1aTZiTjE1R3M4ZlpsTGtpc041aXd2bG9ZV1BUOVJ0TkZ4M1Z3MVZjQ0F3RUFBYU9DQVNNdwpnZ0VmTUFrR0ExVWRFd1FDTUFBd0VRWUpZSVpJQVliNFFnRUJCQVFEQWdaQU1ETUdDV0NHU0FHRytFSUJEUVFtCkZpUlBjR1Z1VTFOTUlFZGxibVZ5WVhSbFpDQlRaWEoyWlhJZ1EyVnlkR2xtYVdOaGRHVXdIUVlEVlIwT0JCWUUKRlBOVmtyR0V3K3J6VTQwa0hQdTErQlVlNk03RU1JR0ZCZ05WSFNNRWZqQjhnQlNhb3M3NGxrQ3dldGZIKzF3SgpCWEpCdkNNbGJLRmZwRjB3V3pFTE1Ba0dBMVVFQmhNQ1ZWTXhEekFOQmdOVkJBZ01Ca1JsYm1saGJERVVNQklHCkExVUVCd3dMVTNCeWFXNW5abWxsYkdReEREQUtCZ05WQkFvTUEwUnBjekVYTUJVR0ExVUVBd3dPZEdOakxuUmwKZEhKaGRHVXVhVytDQXhBQ0VqQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUlLd1lCQlFVSApBd0V3RFFZSktvWklodmNOQVFFTEJRQURnZ0lCQU1XaFdNS0hxZlhyZU1GR2YrTGtXNUNubjcybEVISVFLVW9LCmF0bGFyNWNqUEVYUkVPS3ZPWG8rUGNtRmZKb1NqditSRk94NUNYWFZ6bjUrY25XYW1rb0M4Z3Q4VzJIQUJlVW4KSFNoSXZkVkM0R0lZVGNvUmE1NU10a25MZWtXYWdQWU9UOFYvRFV1ekRrOWlKWmYvbFk3blZTZlFFTU4vaFNuZwo3djd6VGRuem5US2lESW9rbERqQ1FXRGVlc1U4UFFIanQ1UGN4dzZ5U2tUMnc1bmpXajIxeFNDcVJ3RXdLcjZSCkJVdEx3ZEtrSGhGbHkzMkQ5R2pqQ09jWC9MYkNTMDdRVkMrWjRDdVdWaU1Xd3lRaVpQZ3IxRkJzWXV4eHlIZTYKSXJkcDBPMHdIQktTakJsZi8zbzJobnFkL0d0VVRtTTF1K2NCTWYzUTR2VVI4Q0p5SU9PS2ZKd3kwSktSbTk0awpxREtpVTFqczdIQTZhNDU1RVV1Vm5YVlZIMUE0QnZlZ2h4eHVUQTNvQTRkclh6Tm5yTVpZMGRFOWNGcFY1OXF1Clp3YXZ1RUd4cUNGQnBkc0tPdE9yUlA0cmxUQUt5MGY5SGZvTEZFZlRURlk5VUhvVWFiVUtuRm5YMlFlSFY2MEsKc3JpaHp0WEpYQmZnY0l0cjlNTTY4bWV3QXRiY2hKd3BvTVZGd3dPOFk4MEJMQnMyVW9NcjA5R1g3di9Cb3BXNApXcE9ybDM5aE1Cc1Q2S09NRmpKa3l4VmVPWUc3VFFtZnYyR0tZVi8vVlNHVjZacW9kNUorNzBzaSttMEdtWDZpCjlDWm9MamJrZUxGTEtBZytZQWVURTgwcHVVcy8ySHV0RmlROFQ4THNxMm13ckthSXQzckh3UWs5akhjYTlwMUsKSzY2NkVQWmsKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="
  tls.key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBcmxOWE03dE5QTzJFcWNJUDF4bWIxa3ZVeWdCQkJUYVhFOFpLVG5jQWdONVp3b0ozCkEwM05YRVlaQ2gwZmQ4L1VKVldrVDNBcWN1VFQwYmVPRnhSUE1FZmNMNnp4MDdNYUlxRmRFak5CeVJHdndZNmIKRWdWS3J0Z1I5a21PT3dZcDlnbDR0ZjZ0TUVlcUtGUG15RFpHRmJkbkFDN2tDekw5ZUFZUUt6QWROcStObWpYMgp0eklUM0pFUzFmdUxYNXhOZmgxVmk0MW1sM0pNQkpIMk0yQnRGYlcxTWlsa2J5MWhEVFIxZnVNNzVxUVcrY1VnCkNHT1JkakJRK0JlRjdTb01tTmZiZ2pDclJMTVRWV2FpcGZNbUlzOXM2UkI1aGh6QnppTWxXUHFuZEJ3WXZpNkwKcHMzWGtheng5bVV1U0t3M21MQytXaGhZOVAxRzAwWEhkWERWVndJREFRQUJBb0lCQUNhSTU3TFl5WWNaWGdVRQpqK25Wa0Z3N29Rc1NLVTFVdHVxNUgzM2UwbTZxT0I5R0piYkdRUW9QdU1OQ2tzMHlWTXYzOVgxVjV4eEV0d29aCjBFQUx6a0YyOFJaYzNZd1ZnRVo5Y3d4dDVqSGpSZjI4WDAwSmZHdlArWkIrekFFQ0tNNXBZNVNmZW5zOHJFR0QKNG5VSmdrNlVueUVzUEY2NVk4eGZVcjJwUWh2dkx4WGlHZ0RKNHNxeGxVRXJtM2l2S2MvL2w3a3g1U3Ayb0pxNQpTWHpydXpkUDNEQUU3UytLN3dzN25DbVlWL1FoalJOL2RsUnhIOTJKRUZxSGRiMi9CWGUxVzQwUHNTRkJ5MGlOCmsyK3pWNGgzOFJzR1h5NG0yMVc5RVBycmFoRVBvV3RnR0ZLSnhrSFlta2FxMGw5ZVdza1NOcWRMcks3bjdLelMKOEdycGdHa0NnWUVBM2E2cG14VXFOU1JHRzlvWm8zWVI4UmxSY2c3TVkvbHdyVFlFOUVsbkhtUVFjMUdzOUJrcQpmQlhuV0lrWnN5RWFvN1NEUXpmQ3BjRkJuVlkxbm1IcEgveURmV2ZvWitvYVJsRGxmSTBTNlpXRHVoakw3K2plCitENVZuTHlFeTFhK0owUzEwL2c1YkZvYm51NFFwN3pmWTZVdUVsVk1RTElNMTJkSTFmVmtSODBDZ1lFQXlVL3EKbFBFbFZjSmdXUDNodDhWeDdraGtWMlV3QTE3b0l6V2xPdzd3RUNORTBWbVo2UkxnZzQ5NDhxdDBPZ0RuRVZHNQpOelF5WFl5cFU4WTNvN09Ic1dIWGNsUWRmdkVEajBCU3g3OHFBa2E2R01zbkFYTWwrZFFUbXF2VHc0c3BqdEV1CmJ4UUhBRlR3ZXdqeWFsYjhlK09Xd0VkRkVpZWI3QlBlbVJPNkpiTUNnWUE4RkxSL0JaTjA1Nm5ncnBHNFRhMjcKTEdONGlDNDVBa2ZaaWdSNXVOTXIxMjdsOGtMdnZVcFlhdzlTWFlZTG1ITkIzeENjVFNhQ0NnaWdmZGIyWUE3dwp6bDFNeGJhbFF6dHZ4MGtMSXFqM2ljQXoxYmlnQXZzN1NKbW5heWlLZTYzNXNwT2RLVzlXd0cwdis5R2p4SHErCjVPdkJxRUNNWURVK3hBMW5mNlI0R1FLQmdRQ1pEN2MzV1laZWh6VEVWUHhhd3JmV1NacHBUSmxONXNvdmd5bEgKRnh0MTJhc0lWYzBOQm5wSDdUMHpuU0w0dXhqMDlTTVRFdys4U3lldmQ0VjBaUnNseGxPT0xPQmtWUkcweUY1bwpXek93bVdBRFcrc2pVZzZzdmcvTnlSbHdrdzJjOWZVTkpiZ1JDNFB3dUNQQXNMUzE2WndFUSt3RFdyUlZzZUhNCmw5QXZ1d0tCZ1FDOEpsbUY1c3V5TmlNempyZEUzeDJRaElXVTdKM1NRdFl5d0dTdXY3UkVqUGtKTXZLSGxVVmYKZ0JNUk5CZHQ0ZmdOS3l6MzRBOVVQT3pJMm5zb3NQWkliendHTXc2cFFtMU93WElSQWxmcDBUcU91b0FDa3lrSApJdlVHd2pIU2Y3c3V0d1JNbTg1M2MwM2F5N3pnSmZ3Z1FMdjZRK3RzV3VVTThwMjM0ajRVOVE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ=="
---
apiVersion: v1
kind: Secret
metadata:
  name: tsb-iam-jwks
  namespace: tsb
type: Opaque
data:
  jwks: "eyJrZXlzIjpbeyJhbGciOiJSUzI1NiIsImUiOiJBUUFCIiwia3R5IjoiUlNBIiwibiI6InJsTlhNN3ROUE8yRXFjSVAxeG1iMWt2VXlnQkJCVGFYRThaS1RuY0FnTjVad29KM0EwM05YRVlaQ2gwZmQ4X1VKVldrVDNBcWN1VFQwYmVPRnhSUE1FZmNMNnp4MDdNYUlxRmRFak5CeVJHdndZNmJFZ1ZLcnRnUjlrbU9Pd1lwOWdsNHRmNnRNRWVxS0ZQbXlEWkdGYmRuQUM3a0N6TDllQVlRS3pBZE5xLU5talgydHpJVDNKRVMxZnVMWDV4TmZoMVZpNDFtbDNKTUJKSDJNMkJ0RmJXMU1pbGtieTFoRFRSMWZ1TTc1cVFXLWNVZ0NHT1JkakJRLUJlRjdTb01tTmZiZ2pDclJMTVRWV2FpcGZNbUlzOXM2UkI1aGh6QnppTWxXUHFuZEJ3WXZpNkxwczNYa2F6eDltVXVTS3czbUxDLVdoaFk5UDFHMDBYSGRYRFZWdyJ9XX0="
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: tsb
type: Opaque
data:
  config.yaml: "ZGF0YToKICB1c2VybmFtZTogdHNiX3VzZXIKICBwYXNzd29yZDogLS1lbGFzdGljLXVzZXJuYW1l"
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: tsb
type: Opaque
data:
  username: "dHNi"
  password: "OVM4Nk0wMlVTdTVuTHJZWnc0NlZzbzQ4"
---
apiVersion: v1
kind: Secret
metadata:
  name: es-certs
  namespace: tsb
type: Opaque
data:
  ca.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMakNDQWhhZ0F3SUJBZ0lSQUlWTUx3VW90YWVXeHJWTTYyWG80T1V3RFFZSktvWklodmNOQVFFTEJRQXcKSVRFTU1Bb0dBMVVFQ3hNRGRITmlNUkV3RHdZRFZRUURFd2gwYzJJdGFIUjBjREFlRncweU1UQTRNVEF3TURFeQpNalphRncweU1qQTRNVEF3TURJeU1qWmFNQ0V4RERBS0JnTlZCQXNUQTNSellqRVJNQThHQTFVRUF4TUlkSE5pCkxXaDBkSEF3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQy9lL0ZiazNSTkwwMGoKWENIbWV5dEpaZ1NPSU1od3hLZjhCVERoVnpCbGVmYWhYSG1jSDVRY1k2UTdXeThDb2x6UnYyODljRENnVWQ2UwpJaVFEQTl5Mm5XSUFqaWxyczlxMmxrS2ZTQlVpRjVVenU4WHJsRGxPcUo2UVNHZ3Z6VDZxeDc2bFRjNkUzM3VmCnpLeXB5Rk9WT1VtaHZFRUlvR1BFTzRMVytYUDNoOGNEMWgyMWc2cXFNbTN0NnltNHk1NlNIZTh0bkdNcllhY3UKTUhZWU9ZMktEWlV2OGk3MStwT0w4MWdKb3lqeHVYaW1raWNqVG5IUFZhUzV5MXhvSzArdDB5SjY1S0tCK0FGYQo4dkxSR2FOelVKc1RBSk9YK3N4SWtRY3NrYVZ0NzlxN2t5YVZTVHVSRzExVDE2U3g4UWM0eGVqdS8xM1FFdTFHCmlWby9jTDUvQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUNoREFkQmdOVkhTVUVGakFVQmdnckJnRUYKQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVhVjBwR1dsSgpnNFRBTGh5eU16KzhpNWlqendvd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBYWQ5L1EvZ3YzYUcyY01qSDFyCnU4WW1GaDhrRCtpRVg3cGNRVmhkbDdjY2dHNnJZY0NpaGVRZE1RVWxCWXNTZ0lVd0l6Wks2ZEhWL3FJR1VCcmUKV2pxM2hOSjJ5SFRjMSt5SGU4TnpNallYUWhlODFUZUcwZlFrWDA5K3lDSE1rTnhrZVhNK1pZdVhZaHJkbG81VQpoREFZNjFzenFTWkllaC9SNElseE1sTUo1djl2S1V4WjF4Qm9RQ3NvT0NRRGVxV0xNY29SK0JJYy9BVVMwTjR4CkJLbk5yZXR4cUFKQkhRTjl6ZktWTkl1RU54QU12RkRCV2gzRS9NY1pOdXdQSUtlMExnNXNiVDhkdmc1Vis0NXUKeG8yYVBsVVhiOHlQMzZhOHJhcGNVVjFQMHF3c0FwMWdvTzZ0L1R4NTNXeFJ3QXJBVUJiWUlQSkRhOVN5Y0FiWQppZTg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0="
---
apiVersion: v1
kind: Secret
metadata:
  name: ldap-credentials
  namespace: tsb
type: Opaque
data:
  binddn: "Y249YWRtaW4sZGM9dGV0cmF0ZSxkYz1pbw=="
  bindpassword: "YWRtaW4="
---
